#!/bin/bash
REFERENZ="subst_001.htm"
PFAD="/var/www/Dropbox/vp-export/display-leh"

# Alle Dateien löschen, die nicht das selbe Modifikationsdatum haben, wie die REFERENZ-Datei

for DIR in f1 f2
do
DATEOFREF=$(stat -c%y $PFAD/$DIR/$REFERENZ | awk '{ print $1 }') || exit 0


 for FILE in $(ls $PFAD/$DIR/)
 do
   DATEOFFILE=$(stat -c%y $PFAD/$DIR/$FILE | awk '{ print $1 }')
   if [ ! "$DATEOFFILE" == "$DATEOFREF" ]
   then
       rm $PFAD/$DIR/$FILE && echo "$PFAD/$DIR/$FILE wurde gelöscht" || echo "Problem beim Löschen"
   fi
 done
done
