#!/bin/bash

if [[ $1 == "" ]]
then
 echo kein Nutzername angegeben
 exit 1
fi
LOG=/var/log/mail-subst.log
touch $LOG
KOLLEGE=$1

if [ $(date +"%H") -lt 15 ]
then
  if ! $(cat /var/www/Dropbox/vp-export/display-leh/f1/* | grep "Betroffen\|Abwesend" | grep $KOLLEGE > /dev/null) 
  then
    if ! $(cat /var/www/Dropbox/vp-export/display-leh/f2/* | grep "Betroffen\|Abwesend" | grep $KOLLEGE > /dev/null) 
    then
        exit 0
    fi
  fi
else
    if ! $(cat /var/www/Dropbox/vp-export/display-leh/f2/* | grep "Betroffen\|Abwesend" | grep $KOLLEGE > /dev/null)
    then
      if ! $(cat /var/www/Dropbox/vp-export/display-leh/f2/* | grep "Betroffen\|Abwesend" | grep $KOLLEGE > /dev/null)
      then
        exit 0
      fi
    fi
fi





/usr/bin/show-subst $1 | /usr/bin/mail -r "$1@morz.de" -s "Vertretungen für $(date)" "$1@morz.de"

echo "$(date): Für User $1 wurde eine Mail angefordert." >> $LOG
