#!/bin/bash
if [[ $1 == "" ]]
then
 echo kein Nutzername angegeben
 exit 1
fi

# weiter machen nur, wenn 
# es vor 15 Uhr ist und es den Kollegen heute oder morgen betrifft
# oder nach 15 Uhr ist und morgen den Kollegen betrifft. 
if [ $(date +"%H") -lt 15 ]
then
  if ! $(cat /var/www/Dropbox/vp-export/display-leh/f1/* | grep "Betroffen\|Abwesend" | grep $1 > /dev/null) 
  then
    if ! $(cat /var/www/Dropbox/vp-export/display-leh/f2/* | grep "Betroffen\|Abwesend" | grep $1 > /dev/null) 
    then
        exit 0
    fi
  fi
else
    if ! $(cat /var/www/Dropbox/vp-export/display-leh/f2/* | grep Betroffen | grep $1 > /dev/null)
    then
      if ! $(cat /var/www/Dropbox/vp-export/display-leh/f2/* | grep Abwesend | grep $1 > /dev/null)
      then
	exit 0
      fi
    fi
fi

echo "Vertretungen für $1:"

# Heutigen Plan nur dann ausgeben, wenn es vor 16h ist...
if [ $(date +"%H") -lt 16 ]
then
# und wenn es überhaupt was gibt...
  if $(cat /var/www/Dropbox/vp-export/display-leh/f1/* | grep Betroffen | grep $1 > /dev/null) 
  then
   echo
   echo "HEUTE $(date '+%a'):"
   echo " "

   cat /var/www/Dropbox/vp-export/display-leh/f1/* | grep $(date "+%a") \
| grep $1 \
| sed -e 's/</>/g' \
| awk -F'>' '{ print $7 ": " $15 " am " $23 ", " $31 ".Std - " $47  " in Klasse " $39 " Raum " $55 " (" $15 " für " $63 ")" }' \
| sed -e "s/&nbsp;/$1/g" | sed -e "s/---/$1/g" | grep -e "^$1" #| column -t

   echo " "
   echo " "
  fi
# falls abwesend, das noch vermerken:
  if [ "$(cat /var/www/Dropbox/vp-export/display-leh/f1/subst_001.htm | grep Abwesend | grep -c $1)" == "1" ]
  then
    echo Du bist heute ausgeplant
  fi

fi

# morgen nur, wenn es auch was gibt...
if $(cat /var/www/Dropbox/vp-export/display-leh/f2/* | grep Betroffen | grep $1 > /dev/null) 
then
 echo "MORGEN $(date -d 'tomorrow' +'%a'):"
 echo " "

 cat /var/www/Dropbox/vp-export/display-leh/f2/* | grep $(date -d "tomorrow" +"%a") \
| grep $1 \
| sed -e 's/->/verlegt nach/g' \
| sed -e 's/</>/g' \
| awk -F'>' '{ print $7 ": " $15 " am " $23 ", " $31 ".Std - " $47  " in Klasse " $39 " Raum " $55 " (" $15 " für " $63 ")" }' \
| sed -e "s/&nbsp;/$1/g" | sed -e "s/---/$1/g" | grep -e "^$1" #| column -t
fi

# falls abwesend, das noch vermerken:
if [ "$(cat /var/www/Dropbox/vp-export/display-leh/f2/subst_001.htm | grep Abwesend | grep -c $1)" == "1" ]
then
  echo Du bist morgen ausgeplant
fi
